# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build
      working-directory: collector
      run: make package
      
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          **/collector-extension.zip

#     - name: Upload a Build Artifact
#       uses: actions/upload-artifact@v3.1.2
#       with:
#         # Artifact name
#         # A file, directory or wildcard pattern that describes what to upload
#         path: collector/build
        
#   release:
#     runs-on: ubuntu-latest
#     needs: [build]
#     steps:
#     - name: Download a Build Artifact
#       uses: actions/download-artifact@v3.0.2
#     - name: Release
#       uses: softprops/action-gh-release@v1
# #       if: startsWith(github.ref, 'refs/tags/')
#       with:
#         files: Release.txt
# #       with:
# #         # Artifact name
# #         name: # optional
# #         # Destination path
# #         path: # optional
    
